// стили SCSS
import '/src/styles/styleVariables.scss'
import '/src/styles/styleBody.scss'
import '/src/styles/styleHeader.scss'
import '/src/styles/styleMainPhoto.scss'
import '/src/styles/styleSectionСategories.scss'
import '/src/styles/styleMainSlider.scss'
import '/src/styles/styleSliderBestProduct.scss'
import '/src/styles/styleMapAndContacts.scss'
import '/src/styles/styleFooter.scss'
import '/src/styles/styleModalCatalog.scss'
import '/src/styles/promotionalProductsCards.scss'
import '/src/styles/styleModalConstructor/stylePriseListModal.scss'
import '/src/styles/styleModalConstructor/styleOrderAcallModal.scss'
import '/src/styles/styleModalConstructor/styleWentAndWell.scss'
import '/src/styles/styleBasket/styleProductsBlock.scss'
import '/src/styles/styleModalConstructor/stylePlaceAnOrder.scss'


// JavaScript код
import './basketPage'
import './productСategorСards'
import './slider'
import './sliderBestProducts'
import './categoriesModal'
import './promotionalProductsCards/productsHTMLcards'
import './promotionalProductsCards/Database'
import './modalСonstructor/priseListCreateModal'
import './modalСonstructor/modalConstructorDoc'
import './modalСonstructor/orderAcall'
import './modalСonstructor/everythingWentWell'
import './basketDocument/localStorage'
import './basketDocument/removeElement'
import './basketDocument/priseElement'
import './modalСonstructor/placeAnOrder'